version: "3"
services:
  postgres:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
